# FROM node:16 AS build
FROM node:18-alpine AS builder
WORKDIR /app
# COPY package.json package-lock.json ./
# RUN npm install
# COPY . .
# RUN npm run build
COPY public/ ./public
COPY src/ ./src
COPY package.json ./
COPY package-lock.json ./

RUN npm install
RUN npm run build

# Serve the build with Nginx
FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
